### ISSUE TITLE
don't use chdir

### ISSUE THREAD

**Issue by jruderman** [mozilla/mozcommitbuilder#2]
The chdir() call in mozconfigure() makes ximport use the wrong "relative" directory.

Assuming nothing outside of the mozconfigure() function needs the directory changed, this could just be a matter of changing mozconfigure() to use

configureDefault = os.path.join(self.confDir, "config-default")

**Comment by samliu** [comment]
thanks Jesse I'll have a look on Monday

**Comment by samliu** [comment]
fixed as of 6adfcf5
